---

- hosts: all
  become: true
  tasks:

  - name: add apache and php for ubuntu servers
    apt:
      name:
       - libapache2-mod-php
       - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: add apache and php for CentOS servers
    apt:
      name:
       - php
       - httpd
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
