---
- name: Create VM on Nutanix
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create image json file from j2 template
      ansible.builtin.template:
        src: templates/get_image.json.j2
        dest: get_image.json
