- name: install mariadb server package (CentOS)
  tags: centos,db,mariadb
  package:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb server
  tags: db,mariadb,ubuntu
  package:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
